### ISSUE TITLE
Upgrade this project

### ISSUE THREAD

**Issue by lragnarsson** [lragnarsson/Emerald-Engine#12]
... from a course project to a named project for use in this course and more!

What are your thoughts?

Name suggestions?

**Comment by lragnarsson** [comment]
I like the name Emerald.

Maybe Emerald Game Engine, just Emerald, Emerald 3D or Emerald Engine
:gem:

**Comment by hansfilipelo** [comment]
Chaos Emerald? [https://en.wikipedia.org/wiki/Sonic_the_Hedgehog#Chaos_Emeralds](url)

**Comment by lragnarsson** [comment]
My proposal is Emerald Engine - EE.

:)

**Comment by hansfilipelo** [comment]
Go for it.
