### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by dentmaged** [lragnarsson/Emerald-Engine#139]
Just wondering, am I able to use some of the skybox code in my own project? I'll just be using the fragment shader and the sky colour blending (from Skydome.cpp).

**Comment by lragnarsson** [comment]
Yes go ahead! 👍
I added MIT license information to this repo too.

**Comment by hansfilipelo** [comment]
According to the LICENSE file, you are free to use all code under MIT license:

https://github.com/lragnarsson/Emerald-Engine/blob/master/LICENSE

**Comment by hansfilipelo** [comment]
Ha I totally missed that Lage added this a few hours ago (went straight from email notification) 🤗
