### ISSUE TITLE
Frustum culling seems to have some problems

### ISSUE THREAD

**Issue by Isakwiberg** [lragnarsson/Emerald-Engine#30]

**Comment by Isakwiberg** [comment]
Even worse when models scale is big. Spawn a cube with scale around 10 and it wont be visible at all for example.

**Comment by hansfilipelo** [comment]
Lage and I fixed this (I think) for other models. Does this only affect flat-shaded models?

/H-F

**Comment by Isakwiberg** [comment]
Tried just now on scale_model branch and a nanosuit with scale 10 gets culled away from many camera positions. Setting the glClearColor to something other than black lets you try with cubes that are not flat shaded. And they also disappear from many camera positions and angles when they should be visible.

**Comment by hansfilipelo** [comment]
Think this line in Model.cpp could be a problem: 

```
glm::vec3 r_vector = 0.5f * (max_corner - min_corner);
```

The radius isn't half the difference of the max_corner and min_corner - it should be just: 

```
glm::vec3 r_vector = 0.5f * max(max_corner, min_corner);
```

Since the radius is calculated from 0 in model coordinates.

**Comment by hansfilipelo** [comment]
Nope that totally fucked shit up...

**Comment by Isakwiberg** [comment]
Fixed a few days ago. Thank you Erik!
