### ISSUE TITLE
Depth buffer when rendering deferred + flat

### ISSUE THREAD

**Issue by Isakwiberg** [lragnarsson/Emerald-Engine#31]
is not working well together. blitFrameBuffer is the problem.

**Comment by Isakwiberg** [comment]
This might be worth looking in to? At least some investigation to different solutions. 
- One ugly workaround for the demo is of course to let the light sources be drawn like ordinary models when in deferred mode. 

@hansfilipelo, are you experiencing this on your home computer running linux or is this only a mac thing?

**Comment by hansfilipelo** [comment]
This seems to be specific to intels Mac driver, since Lage does not see it with his intel card and elementary.

My Ubuntu machine runs an nvidia card and does not show these errors either. 

Sold my Mac mini with AMD graphics a year ago so can't VERIFY it's specific to intel gpus on Mac.

**Comment by Isakwiberg** [comment]
Finally fixed!
