### ISSUE TITLE
Light attenuation 

### ISSUE THREAD

**Issue by Isakwiberg** [lragnarsson/Emerald-Engine#47]
Tweak these values for our demo

**Comment by lragnarsson** [comment]
Good idea, many fragments get saturated. But we can also tweak the light intensity of our light to be below 1 for this.

**Comment by Isakwiberg** [comment]
Yep. We should also tweak the SSAO so that the effect is visible. Right now with the ambient at 0.1 the effect is not visible but at the same time we do not want too much ambient in our scene so I think we should get creative and try to tweak the deferred lighting so it looks good.

**Comment by Isakwiberg** [comment]
I noticed that if we let the occlusion scale the diffuse part of the lighting as well we get severe banding and aliasing on surfaces far away (which depends on camera location). Increasing the position and normal resolution to RGB32F solves the problem but takes away a few fps on my machine.

What resolution should we have on the position and normals in the g-buffer?

**Comment by Isakwiberg** [comment]
Forward and deferred rendering look the same now when SSAO is off. I think this is OK now
